
      window.addEventListener("load", function() {
        var foamtree_1 = new CarrotSearchFoamTree({
          id: "visualization_yj",
          dataObject: {
          groups: [
                  {"label":"喜 剧",weight:0.568 },
                  {"label":"犯 罪",weight:0.352 },
                  {"label":"悬 疑",weight:0.298 },
                  {"label":"惊 悚",weight:0.160 },
                  {"label":"爱 情",weight:0.108 },
                  {"label":"历 史",weight:0.106 },
                  {"label":"纪 录 片",weight:0.106 },
                  {"label":"科 幻",weight:0.084 },
                  {"label":"奇 幻",weight:0.076 },
                  {"label":"冒 险",weight:0.067 },
                  {"label":"家 庭",weight:0.067 },
                  {"label":"动 作",weight:0.065 },
                  {"label":"战 争",weight:0.052 },
                  {"label":"恐 怖",weight:0.041 },
                  {"label":"传 记",weight:0.037 },
                  {"label":"同 性",weight:0.030 },
                  {"label":"古 装",weight:0.019 },
                  {"label":"动 画",weight:0.015 },
                  {"label":"儿 童",weight:0.013 },
                  {"label":"音 乐",weight:0.009 },
                  {"label":"歌 舞",weight:0.009 },
                  {"label":"灾 难",weight:0.002 },
                  {"label":"运 动",weight:0.000 },
                  {"label":"西 部",weight:0.000 },
                  {"label":"情 色",weight:0.000 },
                  {"label":"武 侠",weight:0.000 }
                  ]},
                    groupMinDiameter: 0,
                    groupSelectionOutlineWidth: 4.3,
                    groupSelectionOutlineColor: "hsla(60, 0%, 100%, 1)",
                    groupFillGradientRadius: 0,
                    groupFillGradientCenterLightnessShift: 0,
                    groupFillGradientRimLightnessShift: 0,
                    groupExposureScale: 1.13,
                    groupUnexposureLightnessShift: 87,
                    rainbowColorDistributionAngle: -180,
                    rainbowLightnessDistributionAngle: -180,
                    rainbowSaturationCorrection: 1,
                    rainbowLightnessCorrection: 0,
                    rainbowStartColor: "#e36e84",
                    rainbowEndColor: "#ffb7b8",
                    rainbowLightnessShift: 0,
                    rainbowLightnessShiftCenter: 0,
                    groupLabelFontFamily: "Songti",
                    groupLabelFontVariant: "small-caps",
                    groupLabelLineHeight: 1,
                    groupLabelVerticalPadding: 0.5,
                    groupLabelMinFontSize: 10,
                    groupLabelMaxFontSize: 60,
                    groupLabelMaxTotalHeight: 0.4,
                    groupLabelDarkColor: "#ffffff",
                    groupLabelColorThreshold: 0,
                    zoomMouseWheelFactor: 1,
                    zoomMouseWheelDuration: 0,
                    attributionPosition: 45 
              });
        var foamtree_2 = new CarrotSearchFoamTree({
          id: "visualization_mj",
          dataObject: {
            groups: [
                  {"label":"喜 剧","weight":0.6188 },
                  {"label":"犯 罪","weight":0.3517 },
                  {"label":"悬 疑","weight":0.3298 },
                  {"label":"惊 悚","weight":0.2576 },
                  {"label":"爱 情","weight":0.1578 },
                  {"label":"历 史","weight":0.0466 },
                  {"label":"纪 录 片","weight":0.0295 },
                  {"label":"科 幻","weight":0.2082 },
                  {"label":"奇 幻","weight":0.1359 },
                  {"label":"冒 险","weight":0.1236 },
                  {"label":"家 庭","weight":0.0970 },
                  {"label":"动 作","weight":0.2196 },
                  {"label":"战 争","weight":0.0247 },
                  {"label":"恐 怖","weight":0.1084 },
                  {"label":"传 记","weight":0.0152 },
                  {"label":"同 性","weight":0.0266 },
                  {"label":"古 装","weight":0.0019 },
                  {"label":"动 画","weight":0.1188 },
                  {"label":"儿 童","weight":0.0029 },
                  {"label":"音 乐","weight":0.0247 },
                  {"label":"歌 舞","weight":0.0057 },
                  {"label":"灾 难","weight":0.0019 },
                  {"label":"运 动","weight":0.0095 },
                  {"label":"西 部","weight":0.0048 },
                  {"label":"情 色","weight":0.0038 },
                  {"label":"武 侠","weight":0.0019 }
                  ]},
                    groupMinDiameter: 0,
                    groupSelectionOutlineWidth: 4.3,
                    groupSelectionOutlineColor: "hsla(60, 0%, 100%, 1)",
                    groupFillGradientRadius: 0,
                    groupFillGradientCenterLightnessShift: 0,
                    groupFillGradientRimLightnessShift: 0,
                    groupExposureScale: 1.13,
                    groupUnexposureLightnessShift: 87,
                    rainbowColorDistributionAngle: -180,
                    rainbowLightnessDistributionAngle: -180,
                    rainbowSaturationCorrection: 1,
                    rainbowLightnessCorrection: 0,
                    rainbowStartColor: "#ff6d6e",
                    rainbowEndColor: "#ffb7b8",
                    rainbowLightnessShift: 0,
                    rainbowLightnessShiftCenter: 0,
                    groupLabelFontFamily: "Songti",
                    groupLabelFontVariant: "small-caps",
                    groupLabelLineHeight: 1,
                    groupLabelVerticalPadding: 0.5,
                    groupLabelMinFontSize: 10,
                    groupLabelMaxFontSize: 60,
                    groupLabelMaxTotalHeight: 0.60,
                    groupLabelDarkColor: "#ffffff",
                    groupLabelColorThreshold: 0,
                    zoomMouseWheelFactor: 1,
                    zoomMouseWheelDuration: 0,
                    attributionPosition: 45  
              });

        var foamtree_3 = new CarrotSearchFoamTree({
          id: "visualization_rj",
          dataObject: {
            groups: [
                  {"label":"喜 剧","weight":0.2489 },
                  {"label":"犯 罪","weight":0.0942 },
                  {"label":"悬 疑","weight":0.1851 },
                  {"label":"惊 悚","weight":0.0195 },
                  {"label":"爱 情","weight":0.2392 },
                  {"label":"历 史","weight":0.0303 },
                  {"label":"纪 录 片","weight":0.0130 },
                  {"label":"科 幻","weight":0.0357 },
                  {"label":"奇 幻","weight":0.0260 },
                  {"label":"冒 险","weight":0.0076 },
                  {"label":"家 庭","weight":0.0628 },
                  {"label":"动 作","weight":0.0411 },
                  {"label":"战 争","weight":0.0119 },
                  {"label":"恐 怖","weight":0.0206 },
                  {"label":"传 记","weight":0.0130 },
                  {"label":"同 性","weight":0.0076 },
                  {"label":"古 装","weight":0.0173 },
                  {"label":"动 画","weight":0.0043 },
                  {"label":"儿 童","weight":0.0108 },
                  {"label":"音 乐","weight":0.0022 },
                  {"label":"歌 舞","weight":0.0000 },
                  {"label":"灾 难","weight":0.0011 },
                  {"label":"运 动","weight":0.0141 },
                  {"label":"西 部","weight":0.0000 },
                  {"label":"情 色","weight":0.0022 },
                  {"label":"武 侠","weight":0.0000 }
                  ]},
                    groupMinDiameter: 0,
                    groupSelectionOutlineWidth: 4.3,
                    groupSelectionOutlineColor: "hsla(60, 0%, 100%, 1)",
                    groupFillGradientRadius: 0,
                    groupFillGradientCenterLightnessShift: 0,
                    groupFillGradientRimLightnessShift: 0,
                    groupExposureScale: 1.13,
                    groupUnexposureLightnessShift: 87,
                    rainbowColorDistributionAngle: -180,
                    rainbowLightnessDistributionAngle: -180,
                    rainbowSaturationCorrection: 1,
                    rainbowLightnessCorrection: 0,
                    // rainbowStartColor: "#eb4a54",
                    // rainbowEndColor: "#ffb7b8",
                    rainbowStartColor: "#33b9d6",
                    rainbowEndColor: "#a8e9fd",
                    rainbowLightnessShift: 0,
                    rainbowLightnessShiftCenter: 0,
                    groupLabelFontFamily: "Songti",
                    groupLabelFontVariant: "small-caps",
                    groupLabelLineHeight: 1,
                    groupLabelVerticalPadding: 0.5,
                    groupLabelMinFontSize: 10,
                    groupLabelMaxFontSize: 60,
                    groupLabelMaxTotalHeight: 0.60,
                    groupLabelDarkColor: "#ffffff",
                    groupLabelColorThreshold: 0,
                    zoomMouseWheelFactor: 1,
                    zoomMouseWheelDuration: 0,
                    attributionPosition: 45  
              });
        var foamtree_4 = new CarrotSearchFoamTree({
          id: "visualization_hj",
          dataObject: {
            groups: [
                  {"label":"喜 剧","weight":0.3110 },
                  {"label":"犯 罪","weight":0.0650 },
                  {"label":"悬 疑","weight":0.0768 },
                  {"label":"惊 悚","weight":0.0315 },
                  {"label":"爱 情","weight":0.7874 },
                  {"label":"历 史","weight":0.0472 },
                  {"label":"纪 录 片","weight":0.0098 },
                  {"label":"科 幻","weight":0.0177 },
                  {"label":"奇 幻","weight":0.0531 },
                  {"label":"冒 险","weight":0.0059 },
                  {"label":"家 庭","weight":0.1299 },
                  {"label":"动 作","weight":0.0394 },
                  {"label":"战 争","weight":0.0020 },
                  {"label":"恐 怖","weight":0.0079 },
                  {"label":"传 记","weight":0.0098 },
                  {"label":"同 性","weight":0.0059 },
                  {"label":"古 装","weight":0.0512 },
                  {"label":"动 画","weight":0.0020 },
                  {"label":"儿 童","weight":0.0000 },
                  {"label":"音 乐","weight":0.0177 },
                  {"label":"歌 舞","weight":0.0020 },
                  {"label":"灾 难","weight":0.0000 },
                  {"label":"运 动","weight":0.0039 },
                  {"label":"西 部","weight":0.0000 },
                  {"label":"情 色","weight":0.0020 },
                  {"label":"武 侠","weight":0.0000 }
                  ]},
                    groupMinDiameter: 0,
                    groupSelectionOutlineWidth: 4.3,
                    groupSelectionOutlineColor: "hsla(60, 0%, 100%, 1)",
                    groupFillGradientRadius: 0,
                    groupFillGradientCenterLightnessShift: 0,
                    groupFillGradientRimLightnessShift: 0,
                    groupExposureScale: 1.13,
                    groupUnexposureLightnessShift: 87,
                    rainbowColorDistributionAngle: -180,
                    rainbowLightnessDistributionAngle: -180,
                    rainbowSaturationCorrection: 1,
                    rainbowLightnessCorrection: 0,
                    rainbowStartColor: "#927ce0",
                    rainbowEndColor: "#c9bcfl",
                    rainbowLightnessShift: 0,
                    rainbowLightnessShiftCenter: 0,
                    groupLabelFontFamily: "Songti",
                    groupLabelFontVariant: "small-caps",
                    groupLabelLineHeight: 1,
                    groupLabelVerticalPadding: 0.5,
                    groupLabelMinFontSize: 10,
                    groupLabelMaxFontSize: 50,
                    groupLabelMaxTotalHeight: 0.60,
                    groupLabelDarkColor: "#ffffff",
                    groupLabelColorThreshold: 0,
                    zoomMouseWheelFactor: 1,
                    zoomMouseWheelDuration: 0,
                    attributionPosition: 45
              });

            var foamtree_5 = new CarrotSearchFoamTree({
          id: "visualization_gcj",
          dataObject: {
            groups: [
                  {"label":"喜 剧","weight":0.1250 },
                  {"label":"犯 罪","weight":0.0516 },
                  {"label":"悬 疑","weight":0.1033 },
                  {"label":"惊 悚","weight":0.0136 },
                  {"label":"爱 情","weight":0.4565 },
                  {"label":"历 史","weight":0.0924 },
                  {"label":"纪 录 片","weight":0.0082 },
                  {"label":"科 幻","weight":0.0082 },
                  {"label":"奇 幻","weight":0.0462 },
                  {"label":"冒 险","weight":0.0000 },
                  {"label":"家 庭","weight":0.1929 },
                  {"label":"动 作","weight":0.0353 },
                  {"label":"战 争","weight":0.0951 },
                  {"label":"恐 怖","weight":0.0054 },
                  {"label":"传 记","weight":0.0299 },
                  {"label":"同 性","weight":0.0000 },
                  {"label":"古 装","weight":0.1984 },
                  {"label":"动 画","weight":0.0000 },
                  {"label":"儿 童","weight":0.0136 },
                  {"label":"音 乐","weight":0.0000 },
                  {"label":"歌 舞","weight":0.0027 },
                  {"label":"灾 难","weight":0.0000 },
                  {"label":"运 动","weight":0.0054 },
                  {"label":"西 部","weight":0.0000 },
                  {"label":"情 色","weight":0.0000 },
                  {"label":"武 侠","weight":0.0217 }
                  ]},
                    groupMinDiameter: 0,
                    groupSelectionOutlineWidth: 4.3,
                    groupSelectionOutlineColor: "hsla(60, 0%, 100%, 1)",
                    groupFillGradientRadius: 0,
                    groupFillGradientCenterLightnessShift: 0,
                    groupFillGradientRimLightnessShift: 0,
                    groupExposureScale: 1.13,
                    groupUnexposureLightnessShift: 87,
                    rainbowColorDistributionAngle: -180,
                    rainbowLightnessDistributionAngle: -180,
                    rainbowSaturationCorrection: 1,
                    rainbowLightnessCorrection: 0,
                    rainbowStartColor: "#ffa88a",
                    rainbowEndColor: "#ffd4c4",
                    rainbowLightnessShift: 0,
                    rainbowLightnessShiftCenter: 0,
                    groupLabelFontFamily: "Songti",
                    groupLabelFontVariant: "small-caps",
                    groupLabelLineHeight: 1,
                    groupLabelVerticalPadding: 0.5,
                    groupLabelMinFontSize: 10,
                    groupLabelMaxFontSize: 60,
                    groupLabelMaxTotalHeight: 0.60,
                    groupLabelDarkColor: "#ffffff",
                    groupLabelColorThreshold: 0,
                    zoomMouseWheelFactor: 1,
                    zoomMouseWheelDuration: 0,
                    attributionPosition: 45
                     
              });
              
          });
